### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by runningsnail2333** [sartorlab/methylSig#23]
hi , i was having trouble in install the package:
![error](https://user-images.githubusercontent.com/26783050/55001167-f57ec180-500e-11e9-9e32-5269eac514d7.png)

please help my solve this problem, thanks!

**Comment by rcavalcante** [comment]
Hi, it looks like this is an issue with the `DelayedArray` package rather than with `methylSig`. I would suggest posting a message on https://support.bioconductor.org.

**Comment by runningsnail2333** [comment]
thank you very much i will try it ~

**Comment by merckey** [comment]
@runningsnail2333 have you figured it out? I'm having the same problem.
Thanks!
