### ISSUE TITLE
Methylation differences output in scientific notation

### ISSUE THREAD

**Issue by rcavalcante** [sartorlab/methylSig#3]
Writing a methylSigDiff object to a file can result in scientific notation for methylation differences when the differences are very small. For example,

`chr14   38340169        38340169        -2.37233043431928e-05`
`chr14   50108792        50108792        -3.51720594760074e-05`
`chr15   99978267        99978267        9.84861037167661e-07`

gives the following error when turning a bedGraph into a bigWig (using `bedGraphToBigWig`):

`invalid unsigned integer: "1.35e+08"`

Perhaps any difference below 0.01 (or some other threshold) should be set to 0?

**Comment by sartorma** [comment]
Yes, adding a minimum limit like 0.01 is fine. I can’t imagine anyone being interested in a difference so small.

**Comment by rcavalcante** [comment]
Fixed with commit e153b3f6cc02761ff6f2515876e880aca8225058 in devel.
