### ISSUE TITLE
Problem with the tile_by_windows() function

### ISSUE THREAD

**Issue by marin-e** [sartorlab/methylSig#48]
Hi, 

I am using MethylSig v1.0.0 on RRBS data. I have a problem with the tile_by_windows() function. I ran tile_by_windows() on this bsseq object : 

```
bs
An object of type 'BSseq' with
  7194960 methylation loci
  9 samples
has not been smoothed
All assays are in-memory
```

Then I applied: 

`windowed_bs <- tile_by_windows(bs = bs, win_size = 25)`
 
And I obtained the following bsseq object: 

```
windowed_bs
An object of type 'BSseq' with
  123890520 methylation loci
  9 samples
has not been smoothed
All assays are in-memory
```

I don't understand why I have more methylation loci after tilling than before.

Do you have an explanation? 

Thank you

**Comment by rcavalcante** [comment]
Hi,

Please see this answer: https://github.com/sartorlab/methylSig/issues/47#issuecomment-660079842

Raymond

**Comment by marin-e** [comment]
Hi, 

Thank you for the clarification (sorry, I didn't realize that the topic was the same that #47).

Marine

**Comment by rcavalcante** [comment]
No problem, I'll go ahead and close the issue. Have a nice day.
