### ISSUE TITLE
Input for methylsig

### ISSUE THREAD

**Issue by Yaseswini** [sartorlab/methylSig#54]
Hi,

I have a methyl call file with 0-based coordinates  .  Can methylsig take 0-based coordinates ? something of this nature -- 
colnames are in the order : chr , start , end , freqC , num of reads supporting C and num of reads supporting T 

 1 chr1  10636 10636  95      38     2
 2 chr1  10617 10617 100      41     0
 3 chr1  10638 10638  97.5    39     1
 4 chr1  10631 10631 100      41     0
 5 chr1  10609 10609  92.5    37     3
 6 chr1  10620 10620  97.5    39     1
 7 chr1  10497 10497  78.3   112    31

Thanks
Yaseswini

**Comment by rcavalcante** [comment]
Hi Yaseswini,

methylSig uses GenomicRanges under the hood, and all coordinates in GenomicRanges are considered to be 1-based, so please be aware of that.

Thanks,
Raymond
