### ISSUE TITLE
Is it possible to use bedgraphs from methyldackel that are not destranded?

### ISSUE THREAD

**Issue by bioinfoMMS** [sartorlab/methylSig#55]
I have a quick question on using the output bedgraphs from methyldackel as input for methylsig. If I run methyldackel without their destranding option (--mergecontext), can bsseq/methylsig destrand it for me? 

For instance, doing this:

bsseq_destranded = bsseq::read.bismark(
    files = files,
    colData = data.frame(row.names = c('test1','test2')),
    rmZeroCov = FALSE,
    strandCollapse = TRUE
)

where the files are bedgraphs from Methyldackel that have not been destranded. 

Thanks!

**Comment by rcavalcante** [comment]
Hi,

Yes, I use the bedgraphs from methyldackel all the time for methylSig. In reality, methylSig uses the `bsseq::read.bismark` function to read in files, and that function handles the bedgraphs just fine.

Thanks,
Raymond

**Comment by bioinfoMMS** [comment]
But does it do the destranding? or does that have be done by Methyldackel beforehand?

**Comment by rcavalcante** [comment]
I think it's more expensive to do the destranding in R than with methyldackel so I'd recommend doing it with methyldackel first.
